### ISSUE TITLE
Does not start with Java 8 update 251

### ISSUE THREAD

**Issue by AndrewMoscoe** [beatngu13/pdf-zoom-wizard#107]
Hi,

I'm on Windows 10 1909, with Java 8 update 251. When I try to run this, I get

Error: Could not find or load main class pdfzoomwizard-0.5.0.jar

Any suggestions?

**Comment by beatngu13** [comment]
Hi @AndrewMoscoe, how do you start the JAR?

**Comment by AndrewMoscoe** [comment]
Tried to double click on it, and nothing happenned.

So I tried to start it from the command line with "java .\pdfzoomwizard-0.5.0.jar"


It's not so important if I can't get it to work, I can fix my bookmarks manually, it would just be a pain.

**Comment by beatngu13** [comment]
When you use the command line, could you try:

```
java -jar pdfzoomwizard-0.5.0.jar
```

That should do the trick.

I know that the first start experience is currently not good, have to work on that.

**Comment by beatngu13** [comment]
@AndrewMoscoe did this solve your issue?

**Comment by AndrewMoscoe** [comment]
Yes, that worked. Thank you!
