### ISSUE TITLE
Don't overwrite file by default

### ISSUE THREAD

**Issue by aaaxx** [beatngu13/pdf-zoom-wizard#157]
I think a better default would be to have the Copy ticked (and infix pre-filled), especially in light of #120. Seems like going with the safer option would make more sense as the default.

Edit: Sorry, this is a feature request, not a bug, but the issues seem to be predefined.

**Comment by beatngu13** [comment]
Hey @aaaxx,

I have thought about this too. Maybe it would also be helpful to remember what the user has selected, similar to #36.

Regarding the bug label: Don't worry, there is currently no other issue template. Will create one for feature requests as well.
