### ISSUE TITLE
jarfile doesnt start on windows

### ISSUE THREAD

**Issue by 0lm** [beatngu13/pdf-zoom-wizard#213]
(i skipped all necessary points, because the jarfile isnt even opening to make a proper bug report).
is there anything i am missing to make it start? i have lots of other java softwares with GUIs and they all start properly. but this one doesnt on windows 10 64bit. is there something special i need to make it work?

when trying to make it run via cmd ( java -jar pdfzoomwizard-0.7.0.jar) I get this error:
Error: Could not find or load main class com.github.beatngu13.pdfzoomwizard.Launcher
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

i do have java 8 update 291 installed

**Comment by 0lm** [comment]
looks like there was a pathing error. i also had some java sdk installed and looks like my enviroment paths had the newest sdk set up instead of java 8

**Comment by beatngu13** [comment]
Thx for reporting back and sorry for the inconvenience. The limitation to Oracle Java 8 is truly a bummer, but I'm already [working on native images](https://github.com/beatngu13/pdf-zoom-wizard/tree/feature/native). Just haven't had time to finalize it…
