### ISSUE TITLE
Error with encrypted PDF

### ISSUE THREAD

**Issue by zenglian** [beatngu13/pdf-zoom-wizard#34]
Reporting a few more bugs.

**Describe the bug**
(1) Fail to process this pdf:  https://1drv.ms/b/s!AgwU0KXODw8-gX_qgyRGZ5ocJZgG
(2) It does not remember the folder (multiple pdf option)
(3) pls rename `log` to log.txt so user does not need to rename it.

**Log**
[log.txt](https://github.com/beatngu13/pdf-zoom-wizard/files/2863647/log.txt)

**Desktop (please complete the following information):**
 - OS: win10
 - Java version: 1.8
 - PDF Zoom Wizard version: 0.2.0

**Additional context**

**Comment by beatngu13** [comment]
Hi @zenglian,

thank you for that detailed report. Unfortunately, I'm not able to download the PDF via the link you have provided. When I click on the download button, I only get a disk image (`.dmg`). And the entire page is in Japanese… 🙃

However, looking at the log file, the last line is:

```
14:31:43.951 [Thread-4] INFO  Wizard - Processing 'Effective Java÷–Œƒ∞Ê µ⁄2∞Ê.pdf.bak'.
```

This file ends with  `.bak`, not `.pdf`, so it appears to be a backup file. This may be related to #29. Have you tried [`v0.3.0`](https://github.com/beatngu13/pdf-zoom-wizard/releases/tag/v0.3.0) of the PDF Zoom Wizard? It should fix that issue.

Regarding your other two suggestion: Please do not mix up multiple issues/enhancements/… within a single issue, create separate issues for them. This makes tracking them a lot more easier for other users and myself. I created them for you:

* #35
* #36

**Comment by zenglian** [comment]
New link: https://1drv.ms/b/s!AgwU0KXODw8-gX_qgyRGZ5ocJZgG

The old page is in Chinese (Japanese is hybrid of Chinese chars and pronouce symbols).

**Comment by beatngu13** [comment]
Thanks @zenglian. The file is encrypted, which doesn't allow modification. From my side there is no plan to support this, but you can [try to decrypt it](https://smallpdf.com/unlock-pdf/) and then move on adapting the bookmarks.

**Comment by zenglian** [comment]
All existing pdfs are converted now!

**Comment by beatngu13** [comment]
Will keep the issue open until I have improved logging / error messages for this.
