### ISSUE TITLE
Never end when processing a PDF file with a lot of bookmarks in Chinese

### ISSUE THREAD

**Issue by kerler** [beatngu13/pdf-zoom-wizard#419]
When processing a sample PDF file with a lot of bookmarks in Chinese, the "PDF Zoom Wizard" is always in status 'Processing', never end. See screen shot below.
![image](https://github.com/beatngu13/pdf-zoom-wizard/assets/1296247/a4ab4597-de60-469a-9865-94af0c76085c)
 
The sample PDF file uploaded. 
[sample.pdf](https://github.com/beatngu13/pdf-zoom-wizard/files/12136148/sample.pdf)

It can also be downloaded from:
https://www.jianguoyun.com/p/Dddr1lcQq43uBRiStJEFIAA

**Comment by kerler** [comment]
Sample PDF uploaded.

[sample.pdf](https://github.com/beatngu13/pdf-zoom-wizard/files/12136138/sample.pdf)

**Comment by kerler** [comment]
Huge log files (12G and 80G in my two tests) were generated. Log shows that "PDF Zoom Wizard" repeat processing line "'??????????????????CBM????????????????????????CBM??????????????????????????????????????????????20%'" (At the position of '?' there are actually Chinese word).

![image](https://github.com/beatngu13/pdf-zoom-wizard/assets/1296247/52f324ab-60c1-4ac3-a12e-816390d01d15)

**Comment by beatngu13** [comment]
Hi @kerler,

thx for the detailed report and the sample PDF.

Will look into the problem the next days. ✌️

**Comment by kerler** [comment]
Last several days I tried another application and met similar problem. The author of that application said that the bookmark in sample.pdf which triggers the error is a self-referring bookmark. We can not see the 'self-referring' attribute in Acrobat or Foxit PDF reader. We do not know how the 'self-referring' bookmark is created. I the past I just use an older version of Foxit PDF reader to create bookmark in PDFs.

I use Foxit PDF reader to remove that error bookmark and re-add it, the error disappear both in pdf-zoom-wizard and another application I mentioned above.

So, if it is the 'self-referring' bookmark which triggers the error, would you like add one or more of the following functions into pdf-zoom-wizard:
1. Check self-referring or recursive (directly or indirectly) bookmarks.
2. Have an option in pdf-zoom-wizard application such as 'recursive_level or recursive_depth' which can be set to 'No Limit' or an integral number.
3. Use 'UTF-8' encoding for the text in the log file so that Chinese words can be displayed correctly.
4. Or even display log message in pdf-zoom-wizard application window.

**Comment by kerler** [comment]
By the way, you may search "20%" in bookmarks in the sample.pdf to find that error bookmark.

**Comment by beatngu13** [comment]
Hi @kerler,

I think I found a fix. Would mind downloading and testing [these artificats](https://github.com/beatngu13/pdf-zoom-wizard/suites/17629255179/artifacts/1007658070) (not part of a release yet)?

**Comment by beatngu13** [comment]
Fix will be part of 0.13.0.
