### ISSUE TITLE
Cannot get it to install or work on Windows 10.

### ISSUE THREAD

**Issue by idsks555** [beatngu13/pdf-zoom-wizard#456]
### Expected Behavior
 pdfzoomwizard-0.12.0.exe- On double click, it should execute, install.

### Actual Behavior

pdfzoomwizard-0.12.0.exe- On double clicking, nothing happens.

### Steps to Reproduce

If possible, please provide a sample PDF and describe the steps to reproduce the behavior:

1. Go to ...
2. Click on ...
3. Scroll down to ...
4. See error ...

### Log

Add the [log file](https://github.com/beatngu13/pdf-zoom-wizard/wiki#info) from `${HOME}/.pdfzoomwizard/log.txt`.

### Environment

- OS: Windows 10 LTSC
- PDF Zoom Wizard version: [e.g. 1.2.3]
- Java version (if use of JAR): jre-8u391-windows-x64.exe

**Comment by beatngu13** [comment]
Hi @idsks555,

Thx for reaching out.

Could please add the [log file](https://github.com/beatngu13/pdf-zoom-wizard/wiki#info)? And do you see any kind of error (message)?

**Comment by beatngu13** [comment]
Hi @oawd,

Hmmm, that's really strange. There have been some internal updates since 0.11.0, I assume this is causing the issue.

ATM I don't have access to a Windows machine, will try to do some tests with a VM.

In the meantime, if you are able to get any logs/messages/…, that would be helpful.

**Comment by idsks555** [comment]
I tried to filter event 'Audit Process Creation' -> Log Success. Then 'Event viewer' security view logged it. But in reality nothing happened with 'Run as administrator'.
[1.txt](https://github.com/beatngu13/pdf-zoom-wizard/files/13760874/1.txt)
[2.txt](https://github.com/beatngu13/pdf-zoom-wizard/files/13760875/2.txt)

'Audit Process Creation' -> Log Failure. Nothing logged in 'Event Viewer'.

**Comment by beatngu13** [comment]
@oawd @idsks555 I just resolved #478, which is released as [0.12.1](https://github.com/beatngu13/pdf-zoom-wizard/releases/tag/v0.12.1). The underlying problem _might_ also caused issues on Windows. Would you mind trying the new release?

**Comment by idsks555** [comment]
I did 'Run as administrator' > chose a file > deselect 'copy' > chose fit WIDTH > RUN (overwrite) > INFO-Succeded. 
But in reality no overwrite occured. The file modified date isn't changed and ALL BOOKMARKS REMAINED 'inherit zoom' mode as they were earlier. The file was not in 'Read-only' mode.
Here is the file and log --> 
[log.txt](https://github.com/beatngu13/pdf-zoom-wizard/files/13805582/log.txt)
[Old_&_New_Testament.pdf](https://github.com/beatngu13/pdf-zoom-wizard/files/13805583/Old_._New_Testament.pdf)

**Comment by beatngu13** [comment]
@idsks555 thx for trying it out!

I'm glad it now launches on Windows 10 again. The log you posted looks like a problem with the underlying PDF lib, different from this issue here. I will open a separate issue and debug it.

**Comment by oawd** [comment]
@beatngu13 Both new versions 0.12.1 and 0.13.0 do launch for me. I did not notice further issues.

**Comment by idsks555** [comment]
@oawd, kindly test with the pdf I linked or any other, is it only my pc or app itself.

**Comment by beatngu13** [comment]
@idsks555 I will keep you updated via #483.
