### ISSUE TITLE
Failed with this pdf

### ISSUE THREAD

**Issue by Yoga9419** [beatngu13/pdf-zoom-wizard#46]
Thank you for your contribution. It works on some of pdfs, but info shows failed for this one, pls help to check the file. Thanks in advance.

http://library1.org/_ads/DBC13AB09234E92E5C169610D1F5E6F6

**Comment by beatngu13** [comment]
Could you please use the [issue template for bug reports](https://github.com/beatngu13/pdf-zoom-wizard/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and complete the missing information? Thank you.

**Comment by Yoga9419** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

Info shows failed for this below pdf:
http://library1.org/_ads/DBC13AB09234E92E5C169610D1F5E6F6

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'single file' mode
2. Click on 'Browse' to open the file in the downloads. 
3. No matter in the coping or overwritten process, the Info shows processing then soon within a half second it becomes failed.

**Expected behavior**
A clear and concise description of what you expected to happen.
In this pdf, the original bookmarks zoom setting is fit page, I'm trying to reset all bookmarks to fit width or inherit zoom.

**Log**
Add the log file from `${HOME}/.pdfzoomwizard/log.txt`.

Sorry...I don't know how to find the log.txt...

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Java version: Java 8 (build 1.8.0_201-b09)
 - PDF Zoom Wizard version: v0.3.0

**Additional context**
Add any other context about the problem here.

**Comment by beatngu13** [comment]
I have just released [v0.4.0](https://github.com/beatngu13/pdf-zoom-wizard/releases/tag/v0.4.0), which should address your issue. Could you please try it out?

**Comment by Yoga9419** [comment]
Wow, it works. Thank you a lot!
