### ISSUE TITLE
*Unable to download the tar file.

### ISSUE THREAD

**Issue by jamesiporter** [beatngu13/pdf-zoom-wizard#484]
### Expected Behavior
pasted the mac command line into Terminal; nothing happened. thanks.

jamesivanporter@gmail.com
### Steps to Reproduce

If possible, please provide a sample PDF and describe the steps to reproduce the behavior:

1. Go to ...
2. Click on ...
3. Scroll down to ...
4. See error ...

### Log

Add the [log file](https://github.com/beatngu13/pdf-zoom-wizard/wiki#info) from `${HOME}/.pdfzoomwizard/log.txt`.

### Environment

- OS: [e.g. macOS 10.14.2]
- PDF Zoom Wizard version: [e.g. 1.2.3]
- Java version (if use of JAR): [e.g. result of `$ java -version`]

**Comment by jamesiporter** [comment]
OK, found the downloadable file. I'm not sure if Zoom level is what I need; will have to explore. Tx

**Comment by beatngu13** [comment]
Thanks for the heads up, the Wiki now includes a link to the releases page:

https://github.com/beatngu13/pdf-zoom-wizard/wiki/Home/_compare/e7d1eb5b71d5d662dc05acc9e61836032ce54932...dc170b8bcaacd244c2dc4f24b2d10a8c62206093
