### ISSUE TITLE
Does not work for this pdf

### ISSUE THREAD

**Issue by zenglian** [beatngu13/pdf-zoom-wizard#60]
I tried zoom level "inherit" and "fit page" but it did not work.

Version: 0.4.1
PDF: https://1drv.ms/b/s!AgwU0KXODw8-ggCc-1EP_Ol3pHRF

Thanks.

**Comment by beatngu13** [comment]
Could please complete the missing information from the [bug report template](https://github.com/beatngu13/pdf-zoom-wizard/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Especially the log would be helpful. In the meantime, I will try to download the 198 MB file…

**Comment by beatngu13** [comment]
Tried it locally and had no problems. As I said, please provide as much information as possible using the template.

**Comment by zenglian** [comment]
Not sure what happened on earth...but it's just working fine for me too...
