### ISSUE TITLE
Having trouble getting started

### ISSUE THREAD

**Issue by QuinGold** [beatngu13/pdf-zoom-wizard#73]
I'm new to GitHub and not a coder. I've installed Java (from the link in the ReadMe) and restarted Mac. OS is up to date. 
I assume I'm suppose to Open "pdfclown.jar" and I right-click to open it with JarLauncher.app. After a few seconds, I get the response "cannot be launched" and to check Console.
I closed all other apps except Safari. Console seems to be saying:
error	17:09:00.280404 -0600	pkd	Failed to find extension point (null) in the binding map, scanning all extension points
error	17:09:00.280445 -0600	pkd	Attempting to merge SDK dictionary into PlugInKit plist <private> but SDK is (null)

Not sure if it's a Security issue, with Mac not wanting to open it. 

Sorry for being clueless. Was expecting a self-contained little app, not a folder of files! So not sure I'm even launching the right file. 

![issue opening jar](https://user-images.githubusercontent.com/53983601/62827717-17c64580-bb92-11e9-81f5-d180a5b0df7a.png)

**Comment by QuinGold** [comment]
This is the list of files I see when the download is automatically Unzipped by Safari/Mac.
![PDF Wizard file list](https://user-images.githubusercontent.com/53983601/62827752-16494d00-bb93-11e9-8a50-9c07a7b5249b.png)

**Comment by beatngu13** [comment]
Hey @QuinGold, thanks for getting back to me. Looks like you have downloaded the source code repository as ZIP, which is the wrong file. You can find the actual releases [here](https://github.com/beatngu13/pdf-zoom-wizard/releases/), the most recent version is [0.4.1](https://github.com/beatngu13/pdf-zoom-wizard/releases/tag/v0.4.1). Download the JAR file (`pdfzoomwizard-0.4.1.jar`) from there and try again, and please let me know if this solved your issue.

**Comment by beatngu13** [comment]
Solved: https://forums.adobe.com/message/11207472#11207472
