### ISSUE TITLE
how to use the JAR-file?

### ISSUE THREAD

**Issue by yippiekahee** [beatngu13/pdf-zoom-wizard#81]
After downloading the JAR file, what do I do with it? If I double click, it simply opens like a ZIP file..

**Comment by beatngu13** [comment]
Hey @yippiekahee, what operating system do you use? And what Java version do you have installed?

**Comment by yippiekahee** [comment]
Windows 10 enterprise
No Java in Program Files, but I do have all kinds of Java stuff in an application called FEWS. In a jre/bin folder, files like java.exe, javaw.exe, javaws.exe, java*.dll, jf*.* etc.

**Comment by beatngu13** [comment]
I assume the Java EXE files in "FEWS" are bundled with this particular application.

I recommend to download and install a separate Java Runtime Environment (JRE) from here:

https://java.com/en/download/

Afterwards, you should be able to double-click and launch the JAR (current version [here](https://github.com/beatngu13/pdf-zoom-wizard/releases/download/v0.4.1/pdfzoomwizard-0.4.1.jar)).

Please let me know if this helps.

**Comment by yippiekahee** [comment]
Surely helps, tnx. Next issue is though that the app only sets first level bookmarks to Inherit zoom. With 2nd & 3rd level my document still jumps to Fit width..

**Comment by beatngu13** [comment]
Glad to here.

Would you mind opening a separate issue for this new problem you encounter? Please use the bug report template, because in this case I need more information to reproduce it (if you can provide the PDF, that would be great).
